### ISSUE TITLE
Yazi 25.2.11 bookmark perisits not work

### ISSUE THREAD

**Issue by 1096015776** [dedukun/bookmarks.yazi#43]
I found this bookmark use 'all' or 'vim' ,it not work.

**Comment by dedukun** [comment]
Hey,

Can you provide more information? Like the output of `yazi --debug` as well as your `init.lua`?
Also do you have other plugins?

**Comment by 1096015776** [comment]
[yazi.log](https://github.com/user-attachments/files/18966903/yazi.log)

**Comment by dedukun** [comment]
I reverted to the fixed release that you are using and it's working for me, though I'm on Linux (though it shouldn't make a difference).

I don't really see anything out of the ordinary in the log, just to make sure you have the `require` correctly enabling this feature in the `init.lua` right? i.e. your `init.lua` looks something like:

```lua
require("bookmarks"):setup({
	last_directory = { enable = true, persist = true },
	persist = "vim",
	desc_format = "full",
	notify = { enable = true },
	file_pick_mode = "hover",
	custom_desc_input = false,
})
```

**Comment by dedukun** [comment]
I'll have access to a mac in the weekend and I'll see if it's a mac specific error, but I don't think it will be the case

**Comment by zikkurat** [comment]
Still doesn't work

===============================================================

Yazi
    Version: 25.4.8 (99ea3b7 2025-04-08)
    Debug  : false
    Triple : x86_64-pc-windows-msvc (windows-x86_64)
    Rustc  : 1.86.0 (05f9846f 2025-03-31)

Ya
    Version: 25.4.8 (99ea3b7 2025-04-08)

Emulator
    TERM                : None
    TERM_PROGRAM        : None
    TERM_PROGRAM_VERSION: None
    Brand.from_env      : Some(Microsoft)
    Emulator.detect     : Emulator { kind: Left(Microsoft), light: false, cell_size: Some((10, 20)) }

Adapter
    Adapter.matches    : Sixel
    Dimension.available: WindowSize { rows: 41, columns: 197, width: 0, height: 0 }

Desktop
    XDG_SESSION_TYPE           : None
    WAYLAND_DISPLAY            : None
    DISPLAY                    : None
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL           : None
    EDITOR          : None
    VISUAL          : None
    YAZI_FILE_ONE   : None
    YAZI_CONFIG_HOME: None
    YAZI_ZOXIDE_OPTS: None
    FZF_DEFAULT_OPTS: None

Text Opener
    default     : Some(OpenerRule { run: "nvim %*", block: true, orphan: false, desc: "", for_: None, spread: true })
    block-create: Some(OpenerRule { run: "nvim %*", block: true, orphan: false, desc: "", for_: None, spread: true })
    block-rename: Some(OpenerRule { run: "nvim %*", block: true, orphan: false, desc: "", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : program not found
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : program not found

Dependencies
    file          : 5.46
    ueberzugpp    : program not found
    ffmpeg/ffprobe: 7.1 / 7.1
    pdftoppm      : 24.08.0
    magick        : 7.1.1-43
    fzf           : 0.60.0
    fd/fdfind     : 10.2.0 / program not found
    rg            : 14.1.1
    chafa         : program not found
    zoxide        : 0.9.7
    7zz/7z        : program not found / 24.09
    jq            : 1.7.1

Clipboard
    wl-copy/paste: program not found / program not found
    xclip        : program not found
    xsel         : program not found

Routine
    `file -bL --mime-type`: text/plain


See https://yazi-rs.github.io/docs/plugins/overview#debugging on how to enable logging or debug runtime errors.

**Comment by ubmarco** [comment]
Have the same issue on Arch Linux x64.

**Comment by nisemono0** [comment]
I had the same issue with `Yazi 25.4.8 (Arch Linux 2025-04-09)`.

In my case, the `~/.local/state/yazi` directory did not exist, hence the `.dds` file was missing and the state was not saved.

After I manually created that directory, persistency works fine for me.

**Comment by wohltat** [comment]
> In my case, the `~/.local/state/yazi` directory did not exist, hence the `.dds` file was missing and the state was not saved.
> 
> After I manually created that directory, persistency works fine for me.

worked for me too. Thanks @nisemono0 

Maybe the bookmarks plugin could create it automatically if it doesn't exist.

This happend for me after copying settings to a new machine where the folder didn't exist.

**Comment by dedukun** [comment]
Hey, sorry for the delay. 

Mmh that directory/file should be created by Yazi itself, so I might create an issue there. I'll do some test in the next couple of days and get back to you

**Comment by nisemono0** [comment]
> Mmh that directory/file should be created by Yazi itself, so I might create an issue there. I'll do some test in the next couple of days and get back to you


I updated to latest `Yazi 25.5.31 (Arch Linux 2025-06-01)` and it seems that the problem is fixed. That directory/file is created when quitting Yazi.

From a quick glance at the logs I found [this,](https://github.com/sxyazi/yazi/pull/2769) which is probably what fixed it.

**Comment by NelsenEW** [comment]
even when i update to 25.5.31, it is still not working yet for my side

**Comment by 1096015776** [comment]
@NelsenEW @ubmarco Hey,I found it work in my macos, I read some document, I just change ~/.config/yazi/main.lua to ~/.config/yazi/init.lua ,it can work well.
